### ISSUE TITLE
Certificate error for s3 servers with Let's Encrypt certificates

### ISSUE THREAD

**Issue by FJEANNOT** [SierraSoftworks/minback-mysql#29]
I'm having a certificate error on a brand new Let's Encrypt certificate on my kubernetes CronJob, i think the ca-certificates are outated on the run image.

I would suggest to add a `update-ca-certificate` on the mysql image on the second stage of the Dockerfile.

**Comment by notheotherben** [comment]
Of course, I've added that package - let me know if the (currently publishing) new image solves this for you.
